-- Add missing item columns (idempotent) for batch_number and extended item fields
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "batch_number" VARCHAR(100);
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "display_name_tamil" VARCHAR(255);
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "hsn_code" VARCHAR(8);
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "gst_rate" DECIMAL(5,2) NOT NULL DEFAULT 0;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "cess_rate" DECIMAL(5,2) NOT NULL DEFAULT 0;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "weight_per_unit" DECIMAL(10,3);
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "volume_per_unit" DECIMAL(10,3);
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "length_per_unit" DECIMAL(10,3);
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "width_per_unit" DECIMAL(10,3);
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "height_per_unit" DECIMAL(10,3);
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "manufacturer" VARCHAR(255);
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "model_number" VARCHAR(100);
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "expiry_date" DATE;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "shelf_life_days" INT;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "min_stock_level" DECIMAL(10,2);
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "max_stock_level" DECIMAL(10,2);
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "reorder_level" DECIMAL(10,2);
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "package_type" VARCHAR(50);
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "package_quantity" INT DEFAULT 1;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "is_perishable" BOOLEAN DEFAULT false;
EXCEPTION WHEN duplicate_column THEN NULL; END $$;
DO $$ BEGIN ALTER TABLE "items" ADD COLUMN "storage_conditions" VARCHAR(255);
EXCEPTION WHEN duplicate_column THEN NULL; END $$;

CREATE INDEX IF NOT EXISTS "items_hsn_code_idx" ON "items"("hsn_code");
